{"Timestamp":"2019-10-12T19:07:44.5359492-04:00","Level":"Error","MessageTemplate":"One or more errors occurred. (One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n))","Exception":"System.AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n))\r\n ---> System.AggregateException: One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n)\r\n ---> System.InvalidOperationException: The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n\r\n ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.<>c.<Attach>b__2_0(Task`1 task)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)\r\n   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)\r\n   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at DotNetCore.AspNetCore.ExceptionMiddleware.InvokeAsync(HttpContext context)","Properties":{"MachineName":"DESKTOP-NM1J6U5","ProcessId":18692,"ThreadId":4}}
{"Timestamp":"2019-10-12T19:07:45.3193182-04:00","Level":"Error","MessageTemplate":"One or more errors occurred. (One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n))","Exception":"System.AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n))\r\n ---> System.AggregateException: One or more errors occurred. (The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n)\r\n ---> System.InvalidOperationException: The NPM script 'development' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:638\r\n\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module 'C:\\Users\\zacha\\source\\repos\\ZRHerr\\PersonalProjects\\QuickFix\\QuickFix.Web\\FrontEnd\\node_modules\\@angular\\cli\\bin\\ng'\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\r\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\r\n    at startup (internal/bootstrap/node.js:283:19)\r\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r\nnpm ERR! code ELIFECYCLE\n\r\nnpm ERR! errno 1\nnpm ERR! frontend@1.0.0 development: `ng lint && ng serve \"--port\" \"61725\"`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the frontend@1.0.0 development script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\n\r\nnpm ERR! A complete log of this run can be found in:\n\r\n\r\n ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.<>c.<Attach>b__2_0(Task`1 task)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)\r\n   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)\r\n   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at DotNetCore.AspNetCore.ExceptionMiddleware.InvokeAsync(HttpContext context)","Properties":{"MachineName":"DESKTOP-NM1J6U5","ProcessId":18692,"ThreadId":4}}
